[package]
name = "extractorb"
version = "0.1.0"
edition = "2021"  # Changed to 2021 as 2024 is not yet standard

[dependencies]
extractous = "0.3.0"
clap = { version = "4.4", features = ["derive"] }
url = "2.4"
anyhow = "1.0"
