name: Build and Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build and Release
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: aarch64-apple-darwin,x86_64-apple-darwin

      # Build for x86_64 (Intel)
      - name: Build release binary (x86_64)
        run: |
          # Set environment variable for static linking
          export RUSTFLAGS="-C target-feature=+crt-static"
          cargo build --release --target x86_64-apple-darwin

      # Build for aarch64 (Apple Silicon)
      - name: Build release binary (aarch64)
        run: |
          # Set environment variable for static linking
          export RUSTFLAGS="-C target-feature=+crt-static"
          cargo build --release --target aarch64-apple-darwin

      - name: Package binaries
        run: |
          mkdir -p dist
          
          # Copy x86_64 binary
          cp target/x86_64-apple-darwin/release/extractorb dist/extractorb-x86_64
          cd dist
          zip -r extractorb-macos-x86_64.zip extractorb-x86_64
          shasum -a 256 extractorb-macos-x86_64.zip > extractorb-macos-x86_64.zip.sha256
          cd ..
          
          # Copy aarch64 binary
          cp target/aarch64-apple-darwin/release/extractorb dist/extractorb-aarch64
          cd dist
          zip -r extractorb-macos-aarch64.zip extractorb-aarch64
          shasum -a 256 extractorb-macos-aarch64.zip > extractorb-macos-aarch64.zip.sha256
          cd ..
          
          # Create universal binary (both architectures)
          cd dist
          lipo -create -output extractorb extractorb-x86_64 extractorb-aarch64
          zip -r extractorb-macos-universal.zip extractorb
          shasum -a 256 extractorb-macos-universal.zip > extractorb-macos-universal.zip.sha256
          cd ..

      # Delete existing tag and release
      - name: Delete existing tag
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'tags/latest'
              });
              console.log('Deleted existing tag');
            } catch (error) {
              console.log('Tag does not exist or could not be deleted');
            }

      # Create a new release
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Latest Build
          body: |
            This is the latest build of extractorb from the main branch.
            
            ## Architecture Options
            
            - Universal binary (works on both Intel and Apple Silicon Macs): extractorb-macos-universal.zip
            - Intel Mac (x86_64): extractorb-macos-x86_64.zip
            - Apple Silicon Mac (aarch64): extractorb-macos-aarch64.zip
            
            ## Installation
            
            ```bash
            # Download (choose one)
            curl -LO https://github.com/michaelneale/extractorb/releases/download/latest/extractorb-macos-universal.zip
            # OR for specific architecture:
            # curl -LO https://github.com/michaelneale/extractorb/releases/download/latest/extractorb-macos-x86_64.zip
            # curl -LO https://github.com/michaelneale/extractorb/releases/download/latest/extractorb-macos-aarch64.zip
            
            # Extract
            unzip extractorb-macos-universal.zip
            
            # Make executable and move to PATH (optional)
            chmod +x extractorb
            sudo mv extractorb /usr/local/bin/
            ```
          files: |
            dist/extractorb-macos-universal.zip
            dist/extractorb-macos-universal.zip.sha256
            dist/extractorb-macos-x86_64.zip
            dist/extractorb-macos-x86_64.zip.sha256
            dist/extractorb-macos-aarch64.zip
            dist/extractorb-macos-aarch64.zip.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}